version: "3"

services:
  db:
    container_name: 'emkk-db'
    image: postgres
    volumes:
      - ./backend/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=emkk_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    ports:
    - "5432:5432"

  backend:
    container_name: 'emkk-backend'
    image: emkk_backend
    build: ./backend
    volumes:
      - ./backend/media:/emkk/backend/media
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=emkk_db
      - DB_USER=admin
      - DB_PASSWORD=pass
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: 'emkk-frontend'
    image: emkk_frontend
    build: ./frontend
    command: npm run start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /emkk/frontend/node_modules
      - ./frontend:/emkk/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
